#ifndef CUSTOM_EVENTS_H_INCLUDED
#define CUSTOM_EVENTS_H_INCLUDED

#define EVENT_WAITING_HEATER(id) {}
#define EVENT_HEATING_FINISHED(id) {}
#define EVENT_TIMER_100MS {}

#endif //CUSTOM_EVENTS_H_INCLUDED
